name: ansys-micro
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.8
    - numpy
    - jsonschema
    - loguru
    - pandas
    - pip
    - pip:
          - ansys-mapdl-core==0.59.3
