name: ansys-micro
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - numpy
    - jsonschema
    - loguru
    - pandas
    - pyvista=0.38
    - pip
    - pip:
          - ansys-mapdl-core==0.63
